name: Deploy to School Ubuntu Server

on:
  push:
    branches:
      - infra/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ssh.gsmsv.site
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ~/GIF_WAB
            git pull origin infra/deploy
            find . -name ".next" -type d -prune -exec rm -rf '{}' +
            docker-compose up --build --no-cache -d
