import { AdminForm, AdminSubmitDetail } from "@/entities/from-management/model/type";

// GET /api/form/admin 응답 mock
export const mockAdminForms: AdminForm[] = [
  {
    id: 1,
    title: "아이디어 페스티벌 보고서",
    deadline: "2026-12-21",
    announced: true,
    submitted: true,
    deadlineComplied: false,
    targetGrade: 1,
    teamName: "VOID",
  },
  {
    id: 2,
    title: "아이디어 페스티벌 보고서",
    deadline: "2026-12-21",
    announced: true,
    submitted: false,
    deadlineComplied: false,
    targetGrade: 1,
    teamName: "GIF",
  },
  {
    id: 3,
    title: "아이디어 페스티벌 보고서",
    deadline: "2026-12-21",
    announced: true,
    submitted: true,
    deadlineComplied: false,
    targetGrade: 1,
    teamName: "NOVA",
  },
  {
    id: 4,
    title: "아이디어 페스티벌 보고서",
    deadline: "2026-12-21",
    announced: true,
    submitted: true,
    deadlineComplied: false,
    targetGrade: 1,
    teamName: "PIXEL",
  },
  {
    id: 5,
    title: "아이디어 페스티벌 배너",
    deadline: "2026-12-31",
    announced: true,
    submitted: true,
    deadlineComplied: false,
    targetGrade: 2,
    teamName: "ALPHA",
  },
  {
    id: 6,
    title: "아이디어 페스티벌 배너",
    deadline: "2026-12-31",
    announced: true,
    submitted: false,
    deadlineComplied: false,
    targetGrade: 2,
    teamName: "BETA",
  },
  {
    id: 7,
    title: "아이디어 페스티벌 배너",
    deadline: "2026-12-31",
    announced: true,
    submitted: true,
    deadlineComplied: false,
    targetGrade: 2,
    teamName: "GAMMA",
  },
];

// GET /api/form/admin/submit?formId={formId} 응답 mock
// 키는 form 템플릿 ID — 해당 양식에 제출한 전체 팀 목록
export const mockSubmitDetailMap: Record<number, AdminSubmitDetail[]> = {
  // formId=1: 아이디어 페스티벌 보고서 — VOID, NOVA, PIXEL
  1: [
    {
      submitId: 1,
      projectId: 1,
      teamName: "VOID",
      submittedByUserId: 101,
      submittedAt: "2026-06-10T09:00:00.000Z",
      answers: [
        {
          fieldId: 1,
          fieldTitle: "팀 관련 사이트 QR코드",
          type: "FILE",
          textAnswer: null,
          filePath: "/mock/void_report.pdf",
          fileSize: 2048000,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
        {
          fieldId: 2,
          fieldTitle: "프로젝트 이름",
          type: "TEXT",
          textAnswer: "저희 프로젝트 이름은 VOID 입니다",
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
        {
          fieldId: 3,
          fieldTitle: "프로젝트 추진 일정",
          type: "CALENDAR",
          textAnswer: null,
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: "기획",
          startDate: "2026-01-05",
          endDate: "2026-01-07",
          color: "yellow",
        },
        {
          fieldId: 3,
          fieldTitle: "프로젝트 추진 일정",
          type: "CALENDAR",
          textAnswer: null,
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: "개발",
          startDate: "2026-01-12",
          endDate: "2026-01-23",
          color: "green",
        },
        {
          fieldId: 3,
          fieldTitle: "프로젝트 추진 일정",
          type: "CALENDAR",
          textAnswer: null,
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: "마무리",
          startDate: "2026-02-01",
          endDate: "2026-02-01",
          color: "red",
        },
      ],
    },
    {
      submitId: 3,
      projectId: 3,
      teamName: "NOVA",
      submittedByUserId: 103,
      submittedAt: "2026-06-11T10:30:00.000Z",
      answers: [
        {
          fieldId: 1,
          fieldTitle: "팀 관련 사이트 QR코드",
          type: "FILE",
          textAnswer: null,
          filePath: "/mock/nova_report.pdf",
          fileSize: 1536000,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
        {
          fieldId: 2,
          fieldTitle: "프로젝트 이름",
          type: "TEXT",
          textAnswer: "NOVA는 별자리를 활용한 앱 서비스입니다.",
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
      ],
    },
    {
      submitId: 4,
      projectId: 4,
      teamName: "PIXEL",
      submittedByUserId: 104,
      submittedAt: "2026-06-12T08:00:00.000Z",
      answers: [
        {
          fieldId: 1,
          fieldTitle: "팀 관련 사이트 QR코드",
          type: "FILE",
          textAnswer: null,
          filePath: "/mock/pixel_qr.pdf",
          fileSize: 512000,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
        {
          fieldId: 2,
          fieldTitle: "프로젝트 이름",
          type: "TEXT",
          textAnswer: "PIXEL - 픽셀아트 공유 플랫폼",
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
        {
          fieldId: 3,
          fieldTitle: "프로젝트 추진 일정",
          type: "CALENDAR",
          textAnswer: null,
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: "UI 설계",
          startDate: "2026-06-08",
          endDate: "2026-06-09",
          color: "yellow",
        },
        {
          fieldId: 3,
          fieldTitle: "프로젝트 추진 일정",
          type: "CALENDAR",
          textAnswer: null,
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: "개발",
          startDate: "2026-06-15",
          endDate: "2026-06-25",
          color: "green",
        },
      ],
    },
  ],

  // formId=2: 아이디어 페스티벌 배너 — ALPHA, GAMMA
  2: [
    {
      submitId: 5,
      projectId: 5,
      teamName: "ALPHA",
      submittedByUserId: 105,
      submittedAt: "2026-06-13T14:00:00.000Z",
      answers: [
        {
          fieldId: 1,
          fieldTitle: "배너 이미지",
          type: "FILE",
          textAnswer: null,
          filePath: "/mock/alpha_banner.png",
          fileSize: 3145728,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
        {
          fieldId: 2,
          fieldTitle: "배너 설명 문구",
          type: "TEXT",
          textAnswer: "미래를 여는 아이디어, ALPHA와 함께",
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
      ],
    },
    {
      submitId: 7,
      projectId: 7,
      teamName: "GAMMA",
      submittedByUserId: 107,
      submittedAt: "2026-06-14T11:00:00.000Z",
      answers: [
        {
          fieldId: 1,
          fieldTitle: "배너 이미지",
          type: "FILE",
          textAnswer: null,
          filePath: "/mock/gamma_banner.pdf",
          fileSize: 4194304,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
        {
          fieldId: 2,
          fieldTitle: "배너 설명 문구",
          type: "TEXT",
          textAnswer: "팀의 개성을 담은 배너로 관람객의 시선을 사로잡고자 했습니다.",
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: null,
          startDate: null,
          endDate: null,
          color: null,
        },
        {
          fieldId: 3,
          fieldTitle: "제작 일정",
          type: "CALENDAR",
          textAnswer: null,
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: "시안 제작",
          startDate: "2026-06-10",
          endDate: "2026-06-12",
          color: "yellow",
        },
        {
          fieldId: 3,
          fieldTitle: "제작 일정",
          type: "CALENDAR",
          textAnswer: null,
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: "수정",
          startDate: "2026-06-20",
          endDate: "2026-06-22",
          color: "red",
        },
        {
          fieldId: 3,
          fieldTitle: "제작 일정",
          type: "CALENDAR",
          textAnswer: null,
          filePath: null,
          fileSize: null,
          dateAnswer: null,
          eventName: "최종 완성",
          startDate: "2026-06-28",
          endDate: "2026-06-28",
          color: "green",
        },
      ],
    },
  ],
};
